# SPDX-License-Identifier: MIT
---
# Put the tasks for your role here.

- name: Set platform/version specific variables
  include_tasks: tasks/set_vars.yml

- name: Ensure required packages are installed on RHEL8 based systems
  package:
    name: "@postgresql:{{ __version }}/server"
    state: present
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"

# RHEL 9 doesn't support modules yet
- name: Ensure required packages are installed on RHEL9 based systems and others
  package:
    name: "postgresql-server"
    state: present
  when:
    - ansible_facts['distribution_major_version'] != "8"

- name: Init DB
  command:
    cmd: postgresql-setup --initdb
    creates: /var/lib/pgsql/data/postgresql.conf
  when:
    - not postgresql_conf.stat.exists

- name: Ensure required services are enabled and started
  service:
    name: "postgresql"
    state: started
    enabled: yes

- name: Check requested and installed version of Postgresql
  fail:
    msg: "Setting version {{ __version }} while ansible_facts.packages['postgresql'][0].version is installed"
  when:
    - "'postgresql' in ansible_facts.packages"
    - "ansible_facts.packages['postgresql'][0].version != {{ __version }}



- name: Generate /etc/{{ __template_foo_config }}
  template:
    src: "{{ __template_foo_config }}.j2"
    dest: /etc/{{ __template_foo_config }}
    backup: yes
    mode: 0400
  notify: template handler to restart services
