---
- name: Gather the packages facts:
  ansible.builtin.package_facts:
    manager: rpm

- name: Check postgresql.conf
    stat:
      path: /var/lib/pgsql/data/postgresql.conf
    register: postgresql_conf

